import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";

const fontCanela = localFont({
  src: [
    {
      path: "../../public/fonts/Canela-Light-Trial.otf",
    },
  ],
  variable: '--font-canela',
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "800", "900"],
});


export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  icons: "http://localhost:3000/favicon-50.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body  className= {`${poppins.className} ${fontCanela.variable} bg-gradient-to-r from-white to-slate-400 `}>{children}</body>
    </html>
  );
}
